/**
 * Phase 43: Canonical Event Definitions & Metadata
 * Logistics standard events for Ocean, Air, Trucking, Customs, and Exceptions
 */

import { EventTypeDefinition, LogisticsEventType } from '../../types/shipmentEvent';

export const LOGISTICS_EVENT_DEFINITIONS: EventTypeDefinition[] = [
  // 1. Preparation & Booking
  {
    type: 'BOOKING_REQUESTED',
    category: 'PREPARATION',
    titleVi: 'Yêu cầu Đặt chỗ (Booking Requested)',
    titleEn: 'Booking Requested',
    defaultMilestoneCode: 'BOOKING_REQUESTED',
    color: 'amber',
    iconName: 'BookmarkPlus',
  },
  {
    type: 'BOOKING_CONFIRMED',
    category: 'PREPARATION',
    titleVi: 'Xác nhận Booking (Booking Confirmed)',
    titleEn: 'Booking Confirmed',
    defaultMilestoneCode: 'BOOKING_CONFIRMED',
    color: 'blue',
    iconName: 'FileCheck',
  },
  {
    type: 'SI_SUBMITTED',
    category: 'PREPARATION',
    titleVi: 'Đã nộp Chi tiết hướng dẫn vận chuyển (SI Submitted)',
    titleEn: 'Shipping Instruction (SI) Submitted',
    defaultMilestoneCode: 'BOOKING_CONFIRMED',
    color: 'blue',
    iconName: 'Send',
  },
  {
    type: 'VGM_SUBMITTED',
    category: 'PREPARATION',
    titleVi: 'Đã xác nhận Khối lượng toàn bộ (VGM Submitted)',
    titleEn: 'VGM Weight Declaration Submitted',
    defaultMilestoneCode: 'CONTAINER_GATE_OUT',
    color: 'indigo',
    iconName: 'Scale',
  },

  // 2. Cargo & Container Handling
  {
    type: 'CARGO_READY',
    category: 'CARGO',
    titleVi: 'Hàng sẵn sàng tại kho xuất (Cargo Ready)',
    titleEn: 'Cargo Ready for Pickup',
    defaultMilestoneCode: 'CARGO_PICKED_UP',
    color: 'indigo',
    iconName: 'PackageCheck',
  },
  {
    type: 'CARGO_RECEIVED_TERMINAL',
    category: 'CARGO',
    titleVi: 'Hàng đã nhập kho sân bay / bãi cảng (Terminal Received)',
    titleEn: 'Cargo Received at Terminal',
    defaultMilestoneCode: 'CARGO_PICKED_UP',
    color: 'indigo',
    iconName: 'Warehouse',
  },
  {
    type: 'CONTAINER_RELEASED_EMPTY',
    category: 'CARGO',
    titleVi: 'Cấp vỏ container rỗng tại Depot (Empty Released)',
    titleEn: 'Empty Container Released at Depot',
    defaultMilestoneCode: 'CARGO_PICKED_UP',
    color: 'cyan',
    iconName: 'Box',
  },
  {
    type: 'CONTAINER_STUFFED',
    category: 'CARGO',
    titleVi: 'Đã đóng hàng vào container & bấm chì (Stuffed & Sealed)',
    titleEn: 'Container Stuffed & Sealed',
    defaultMilestoneCode: 'CARGO_PICKED_UP',
    color: 'cyan',
    iconName: 'ShieldCheck',
  },
  {
    type: 'CONTAINER_GATE_IN_POL',
    category: 'CARGO',
    titleVi: 'Hạ bãi xuất khẩu Cảng xuất (CY Gate In / Cut-off)',
    titleEn: 'Container Gate In at POL Terminal',
    defaultMilestoneCode: 'CONTAINER_GATE_OUT',
    color: 'blue',
    iconName: 'Truck',
  },

  // 3. Customs
  {
    type: 'CUSTOMS_DOCS_RECEIVED',
    category: 'CUSTOMS',
    titleVi: 'Đã tiếp nhận hồ sơ chứng từ hải quan (Docs Received)',
    titleEn: 'Customs Documents Received',
    defaultMilestoneCode: 'CUSTOMS_STARTED',
    color: 'purple',
    iconName: 'Files',
  },
  {
    type: 'CUSTOMS_DECLARATION_SUBMITTED',
    category: 'CUSTOMS',
    titleVi: 'Đã truyền tờ khai VNACCS (Declaration Submitted)',
    titleEn: 'Customs Declaration Submitted',
    defaultMilestoneCode: 'CUSTOMS_STARTED',
    color: 'purple',
    iconName: 'Send',
  },
  {
    type: 'CUSTOMS_CHANNEL_ASSIGNED',
    category: 'CUSTOMS',
    titleVi: 'Đã phân luồng tờ khai (Xanh / Vàng / Đỏ)',
    titleEn: 'Customs Channel Assigned',
    defaultMilestoneCode: 'CUSTOMS_STARTED',
    color: 'purple',
    iconName: 'GitBranch',
  },
  {
    type: 'CUSTOMS_CLEARED',
    category: 'CUSTOMS',
    titleVi: 'Thông quan xuất/nhập khẩu thành công (Customs Cleared)',
    titleEn: 'Customs Cleared',
    defaultMilestoneCode: 'CUSTOMS_CLEARED',
    color: 'emerald',
    iconName: 'CheckCheck',
  },

  // 4. Main Carriage (Ocean / Air)
  {
    type: 'LOADED_ON_BOARD',
    category: 'MAIN_CARRIAGE',
    titleVi: 'Xếp hàng lên tàu / máy bay (Loaded on Board)',
    titleEn: 'Loaded on Board',
    defaultMilestoneCode: 'LOADED_ON_VESSEL',
    color: 'sky',
    iconName: 'Ship',
  },
  {
    type: 'VESSEL_DEPARTED',
    category: 'MAIN_CARRIAGE',
    titleVi: 'Tàu khởi hành cảng đi (ATD - Vessel Departed)',
    titleEn: 'Vessel Departed (ATD)',
    defaultMilestoneCode: 'VESSEL_DEPARTED',
    color: 'indigo',
    iconName: 'Navigation',
  },
  {
    type: 'FLIGHT_DEPARTED',
    category: 'MAIN_CARRIAGE',
    titleVi: 'Chuyến bay cất cánh (ATD - Flight Departed)',
    titleEn: 'Flight Departed (ATD)',
    defaultMilestoneCode: 'VESSEL_DEPARTED',
    color: 'sky',
    iconName: 'PlaneTakeoff',
  },
  {
    type: 'TRANSSHIPMENT_ARRIVED',
    category: 'MAIN_CARRIAGE',
    titleVi: 'Cập cảng chuyển tải (Transshipment Arrived)',
    titleEn: 'Transshipment Port Arrival',
    defaultMilestoneCode: 'TRANSSHIPMENT',
    color: 'blue',
    iconName: 'Anchor',
  },
  {
    type: 'TRANSSHIPMENT_DEPARTED',
    category: 'MAIN_CARRIAGE',
    titleVi: 'Rời cảng chuyển tải (Transshipment Departed)',
    titleEn: 'Transshipment Port Departure',
    defaultMilestoneCode: 'TRANSSHIPMENT',
    color: 'blue',
    iconName: 'Navigation2',
  },
  {
    type: 'VESSEL_ARRIVED',
    category: 'MAIN_CARRIAGE',
    titleVi: 'Tàu cập cảng đến (ATA - Vessel Arrived)',
    titleEn: 'Vessel Arrived at POD (ATA)',
    defaultMilestoneCode: 'VESSEL_ARRIVED',
    color: 'teal',
    iconName: 'Anchor',
  },
  {
    type: 'FLIGHT_ARRIVED',
    category: 'MAIN_CARRIAGE',
    titleVi: 'Chuyến bay hạ cánh (ATA - Flight Arrived)',
    titleEn: 'Flight Arrived (ATA)',
    defaultMilestoneCode: 'VESSEL_ARRIVED',
    color: 'teal',
    iconName: 'PlaneLanding',
  },
  {
    type: 'CONTAINER_DISCHARGED',
    category: 'MAIN_CARRIAGE',
    titleVi: 'Dỡ hàng/container khỏi phương tiện (Discharged)',
    titleEn: 'Container Discharged at POD',
    defaultMilestoneCode: 'DISCHARGED',
    color: 'cyan',
    iconName: 'ArrowDownToLine',
  },

  // 5. Inland Delivery & Handover
  {
    type: 'TRUCKING_DISPATCHED',
    category: 'DELIVERY',
    titleVi: 'Điều phối xe vận chuyển nội địa (Truck Dispatched)',
    titleEn: 'Inland Truck Dispatched',
    defaultMilestoneCode: 'DELIVERY_STARTED',
    color: 'orange',
    iconName: 'Truck',
  },
  {
    type: 'TRUCK_IN_TRANSIT',
    category: 'DELIVERY',
    titleVi: 'Xe đang trên đường giao hàng (Out for Delivery)',
    titleEn: 'Out for Inland Delivery',
    defaultMilestoneCode: 'DELIVERY_STARTED',
    color: 'orange',
    iconName: 'Route',
  },
  {
    type: 'DELIVERED_CONSIGNEE',
    category: 'DELIVERY',
    titleVi: 'Hàng đã giao tới kho người nhận (Delivered to Consignee)',
    titleEn: 'Cargo Delivered to Consignee',
    defaultMilestoneCode: 'DELIVERED',
    color: 'emerald',
    iconName: 'MapPinCheck',
  },
  {
    type: 'POD_SIGNED',
    category: 'DELIVERY',
    titleVi: 'Đã nhận Biên bản giao hàng có chữ ký (POD Signed)',
    titleEn: 'Proof of Delivery (POD) Signed',
    defaultMilestoneCode: 'DELIVERED',
    color: 'emerald',
    iconName: 'FileSignature',
  },
  {
    type: 'CONTAINER_EMPTY_RETURNED',
    category: 'DELIVERY',
    titleVi: 'Trả vỏ container rỗng về Depot hãng tàu (Empty Returned)',
    titleEn: 'Empty Container Returned to Depot',
    defaultMilestoneCode: 'EMPTY_RETURNED',
    color: 'slate',
    iconName: 'CornerDownLeft',
  },

  // 6. Operational Events & Exceptions
  {
    type: 'SHIPMENT_DELAY_REPORTED',
    category: 'OPERATIONAL',
    titleVi: 'Báo cáo chậm trễ / thay đổi lịch (Delay Reported)',
    titleEn: 'Operational Delay Reported',
    color: 'rose',
    iconName: 'ClockAlert',
  },
  {
    type: 'EXCEPTION_RAISED',
    category: 'OPERATIONAL',
    titleVi: 'Ghi nhận sự cố vận hành (Exception Raised)',
    titleEn: 'Operational Exception Raised',
    color: 'rose',
    iconName: 'AlertTriangle',
  },
  {
    type: 'EXCEPTION_RESOLVED',
    category: 'OPERATIONAL',
    titleVi: 'Đã xử lý xong sự cố vận hành (Exception Resolved)',
    titleEn: 'Operational Exception Resolved',
    color: 'emerald',
    iconName: 'CheckCircle2',
  },
  {
    type: 'OPERATIONAL_NOTE_ADDED',
    category: 'OPERATIONAL',
    titleVi: 'Ghi chú điều hành nội bộ (Operational Note)',
    titleEn: 'Operational Note Added',
    color: 'slate',
    iconName: 'MessageSquareText',
  },
  {
    type: 'DOCUMENT_UPLOADED',
    category: 'OPERATIONAL',
    titleVi: 'Tải lên chứng từ tác nghiệp (Document Uploaded)',
    titleEn: 'Operational Document Uploaded',
    color: 'blue',
    iconName: 'FileUp',
  },
  {
    type: 'CUSTOM_EVENT',
    category: 'OPERATIONAL',
    titleVi: 'Sự kiện vận hành khác (Custom Event)',
    titleEn: 'Custom Operational Event',
    color: 'slate',
    iconName: 'Activity',
  },
];

export function getEventDefinition(type: LogisticsEventType): EventTypeDefinition {
  const found = LOGISTICS_EVENT_DEFINITIONS.find(d => d.type === type);
  if (found) return found;

  return {
    type,
    category: 'OPERATIONAL',
    titleVi: `Sự kiện: ${type}`,
    titleEn: `Event: ${type}`,
    color: 'slate',
    iconName: 'Activity',
  };
}
